# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/need_url.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 106)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 20, 221, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.InfoLabel = QtWidgets.QLabel(self.layoutWidget)
        self.InfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InfoLabel.setObjectName("InfoLabel")
        self.gridLayout.addWidget(self.InfoLabel, 0, 0, 1, 1)
        self.CloseButton = QtWidgets.QPushButton(self.layoutWidget)
        self.CloseButton.setObjectName("CloseButton")
        self.gridLayout.addWidget(self.CloseButton, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.InfoLabel.setText(_translate("Dialog", "Missing or invalid URL."))
        self.CloseButton.setText(_translate("Dialog", "Close"))
