# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\application_doesnt_exist.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApplicationDoesntExist(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(487, 95)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.DoesntExistLabel = QtWidgets.QLabel(Dialog)
        self.DoesntExistLabel.setText("")
        self.DoesntExistLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DoesntExistLabel.setObjectName("DoesntExistLabel")
        self.gridLayout.addWidget(self.DoesntExistLabel, 0, 0, 1, 1)
        self.OKButton = QtWidgets.QPushButton(Dialog)
        self.OKButton.setObjectName("OKButton")
        self.gridLayout.addWidget(self.OKButton, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.OKButton.setText(_translate("Dialog", "OK"))
