# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/file_exists.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileExistsDialog(object):
    def setupUi(self, FileExistsDialog):
        FileExistsDialog.setObjectName("FileExistsDialog")
        FileExistsDialog.resize(437, 135)
        self.gridLayout_2 = QtWidgets.QGridLayout(FileExistsDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(31)
        self.gridLayout.setObjectName("gridLayout")
        self.FileExistsLabel = QtWidgets.QLabel(FileExistsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileExistsLabel.sizePolicy().hasHeightForWidth())
        self.FileExistsLabel.setSizePolicy(sizePolicy)
        self.FileExistsLabel.setText("")
        self.FileExistsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FileExistsLabel.setObjectName("FileExistsLabel")
        self.gridLayout.addWidget(self.FileExistsLabel, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(80, -1, 80, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NoButton = QtWidgets.QPushButton(FileExistsDialog)
        self.NoButton.setObjectName("NoButton")
        self.horizontalLayout.addWidget(self.NoButton)
        self.YesButton = QtWidgets.QPushButton(FileExistsDialog)
        self.YesButton.setObjectName("YesButton")
        self.horizontalLayout.addWidget(self.YesButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(FileExistsDialog)
        QtCore.QMetaObject.connectSlotsByName(FileExistsDialog)

    def retranslateUi(self, FileExistsDialog):
        _translate = QtCore.QCoreApplication.translate
        FileExistsDialog.setWindowTitle(_translate("FileExistsDialog", "File Already Exists"))
        self.NoButton.setText(_translate("FileExistsDialog", "No"))
        self.YesButton.setText(_translate("FileExistsDialog", "Yes"))
