# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoDialog(object):
    def setupUi(self, InfoDialog):
        InfoDialog.setObjectName("InfoDialog")
        InfoDialog.resize(636, 300)
        self.widget = QtWidgets.QWidget(InfoDialog)
        self.widget.setGeometry(QtCore.QRect(20, 30, 608, 241))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.URLLabel = QtWidgets.QLabel(self.widget)
        self.URLLabel.setWordWrap(True)
        self.URLLabel.setObjectName("URLLabel")
        self.verticalLayout.addWidget(self.URLLabel)
        self.MetaLabel = QtWidgets.QLabel(self.widget)
        self.MetaLabel.setWordWrap(True)
        self.MetaLabel.setObjectName("MetaLabel")
        self.verticalLayout.addWidget(self.MetaLabel)
        self.TrimLabel = QtWidgets.QLabel(self.widget)
        self.TrimLabel.setWordWrap(True)
        self.TrimLabel.setObjectName("TrimLabel")
        self.verticalLayout.addWidget(self.TrimLabel)
        self.FolderLabel = QtWidgets.QLabel(self.widget)
        self.FolderLabel.setWordWrap(True)
        self.FolderLabel.setObjectName("FolderLabel")
        self.verticalLayout.addWidget(self.FolderLabel)
        self.FilenameLabel = QtWidgets.QLabel(self.widget)
        self.FilenameLabel.setWordWrap(True)
        self.FilenameLabel.setObjectName("FilenameLabel")
        self.verticalLayout.addWidget(self.FilenameLabel)
        self.FormatLabel = QtWidgets.QLabel(self.widget)
        self.FormatLabel.setWordWrap(True)
        self.FormatLabel.setObjectName("FormatLabel")
        self.verticalLayout.addWidget(self.FormatLabel)

        self.retranslateUi(InfoDialog)
        QtCore.QMetaObject.connectSlotsByName(InfoDialog)

    def retranslateUi(self, InfoDialog):
        _translate = QtCore.QCoreApplication.translate
        InfoDialog.setWindowTitle(_translate("InfoDialog", "Dialog"))
        self.URLLabel.setText(_translate("InfoDialog", "URL: Link to the Youtube video. Only required piece of information"))
        self.MetaLabel.setText(_translate("InfoDialog", "Title, Artist, Genre: Optional metadata can be added to the downloaded file"))
        self.TrimLabel.setText(_translate("InfoDialog", "Start time, End time: Amount of seconds from beginning and end to trim the audio file"))
        self.FolderLabel.setText(_translate("InfoDialog", "Choose Folder: If no folder is chosen, defaults to home directory. Saves chosen folder each time"))
        self.FilenameLabel.setText(_translate("InfoDialog", "Filename: If no filename is entered, default is the title of the Youtube video. Do not enter the extension"))
        self.FormatLabel.setText(_translate("InfoDialog", "List Formats: Lists the available formats of the downloaded video. Default is .m4a"))
