# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/invalid_time.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InvalidTime(object):
    def setupUi(self, InvalidTime):
        InvalidTime.setObjectName("InvalidTime")
        InvalidTime.resize(400, 110)
        self.layoutWidget = QtWidgets.QWidget(InvalidTime)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 20, 241, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.CloseButton = QtWidgets.QPushButton(self.layoutWidget)
        self.CloseButton.setObjectName("CloseButton")
        self.gridLayout.addWidget(self.CloseButton, 1, 0, 1, 1)

        self.retranslateUi(InvalidTime)
        QtCore.QMetaObject.connectSlotsByName(InvalidTime)

    def retranslateUi(self, InvalidTime):
        _translate = QtCore.QCoreApplication.translate
        InvalidTime.setWindowTitle(_translate("InvalidTime", "Dialog"))
        self.label.setText(_translate("InvalidTime", "Invalid start or end time."))
        self.CloseButton.setText(_translate("InvalidTime", "Close"))
